"""Trading strategy implementations."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any, List
import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    timestamp: pd.Timestamp
    price: float
    confidence: float = 1.0
    metadata: Dict[str, Any] = None


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""
    
    def __init__(self, name: str, params: Optional[Dict[str, Any]] = None):
        self.name = name
        self.params = params or {}
        self._initialized = False
    
    @abstractmethod
    def initialize(self, data: pd.DataFrame) -> None:
        """Initialize the strategy with historical data."""
        pass
    
    @abstractmethod
    def on_data(self, data: pd.DataFrame) -> Optional[Signal]:
        """Process new data and generate signals."""
        pass
    
    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters."""
        pass
    
    def set_parameters(self, params: Dict[str, Any]) -> None:
        """Update strategy parameters."""
        self.params.update(params)
