"""Trading strategy implementations."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
import inspect
from typing import Optional, Dict, Any
import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    timestamp: pd.Timestamp
    price: float
    confidence: float = 1.0
    metadata: Dict[str, Any] = None


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    def __init__(self, name: str, params: Optional[Dict[str, Any]] = None):
        self.name = name
        self.params = params or {}
        self._initialized = False

    @abstractmethod
    def initialize(self, data: pd.DataFrame) -> None:
        """Initialize the strategy with historical data."""
        pass

    @abstractmethod
    def on_data(self, data: pd.DataFrame) -> Optional[Signal]:
        """Process new data and generate signals."""
        pass

    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters."""
        pass

    def set_parameters(self, params: Dict[str, Any]) -> None:
        """Update strategy parameters."""
        self.params.update(params)


@dataclass(frozen=True)
class StrategyDefinition:
    """Beginner-friendly strategy metadata for CLI discovery."""

    name: str
    description: str
    default_params: Dict[str, Any]


def list_strategies() -> list[str]:
    """Return registered strategy names."""
    return sorted(list(_STRATEGY_REGISTRY.keys()))


def get_strategy(name: str):
    """Get a strategy class by name (case-insensitive)."""
    if not name:
        return None
    return _STRATEGY_REGISTRY.get(name.lower())


def create_strategy(name: str, params: Optional[Dict[str, Any]] = None):
    """Create strategy instance from registry by name."""
    strategy_cls = get_strategy(name)
    if strategy_cls is None:
        available = ", ".join(list_strategies())
        raise ValueError(f"Unknown strategy '{name}'. Available: {available}")
    return strategy_cls(params)


def describe_strategy(name: str) -> Optional[StrategyDefinition]:
    """Return strategy description and defaults for CLI/help output."""
    strategy_cls = get_strategy(name)
    if strategy_cls is None:
        return None

    strategy = create_strategy(name)
    doc = inspect.getdoc(strategy_cls) or ""
    summary = doc.splitlines()[0].strip() if doc else strategy.name
    return StrategyDefinition(
        name=name.lower(),
        description=summary,
        default_params=strategy.get_parameters(),
    )


def describe_strategies() -> list[StrategyDefinition]:
    """Return discovery metadata for all registered strategies."""
    descriptions: list[StrategyDefinition] = []
    for name in list_strategies():
        strategy = describe_strategy(name)
        if strategy is not None:
            descriptions.append(strategy)
    return descriptions


_STRATEGY_REGISTRY = {}


def _import_strategy(module_name: str, class_name: str):
    module = __import__(f"{__name__}.{module_name}", fromlist=[class_name])
    return getattr(module, class_name)


def _register_strategy(name: str, module_name: str, class_name: str) -> None:
    if name not in _STRATEGY_REGISTRY:
        _STRATEGY_REGISTRY[name] = _import_strategy(module_name, class_name)


_register_strategy("sma_crossover", "sma_crossover", "SmaCrossoverStrategy")
_register_strategy("sma_crossover_risk", "sma_crossover_risk", "SmaCrossoverRiskStrategy")
