"""Base algorithm interface for trading strategies."""

import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional, Dict, Any, List, Callable
from datetime import datetime
from enum import Enum

import pandas as pd

from adapters.base_adapter import Order, OrderSide, OrderType, Ticker
from order_management.order_manager import OrderRequest, OrderManager
from risk_management.risk_manager import RiskManager
from log_config import TradingLogger


class AlgorithmState(Enum):
    """Algorithm execution state."""
    INITIALIZING = "initializing"
    READY = "ready"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"


@dataclass
class Signal:
    """Trading signal generated by an algorithm."""
    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    timestamp: datetime
    price: Decimal
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Optional order parameters
    order_type: OrderType = OrderType.MARKET
    quantity: Optional[Decimal] = None
    stop_loss_pct: Optional[float] = None
    take_profit_pct: Optional[float] = None


@dataclass
class AlgorithmConfig:
    """Algorithm configuration."""
    name: str
    symbols: List[str]
    timeframe: str = "1h"
    lookback_periods: int = 100
    
    # Risk parameters
    max_position_size: Optional[Decimal] = None
    max_risk_per_trade: Optional[float] = None
    
    # Execution parameters
    use_bracket_orders: bool = True
    wait_for_fill: bool = False


class BaseAlgorithm(ABC):
    """Abstract base class for all trading algorithms.
    
    All trading strategies must inherit from this class and implement:
    - initialize(): Set up indicators with historical data
    - on_data(): Process new data and generate signals
    - on_execute(): Execute trading decisions
    - on_order_filled(): Handle order fill events
    
    The class provides:
    - Integration with OrderManager for order execution
    - Integration with RiskManager for risk checks
    - Signal generation and processing
    - State management
    """
    
    def __init__(
        self,
        config: AlgorithmConfig,
        order_manager: Optional[OrderManager] = None,
        risk_manager: Optional[RiskManager] = None
    ):
        self.config = config
        self.order_manager = order_manager
        self.risk_manager = risk_manager
        self.logger = TradingLogger(f"Algorithm.{config.name}")
        
        # State
        self.state = AlgorithmState.INITIALIZING
        self._initialized = False
        
        # Data storage
        self.data: Dict[str, pd.DataFrame] = {}
        self.current_prices: Dict[str, Decimal] = {}
        
        # Position tracking
        self.positions: Dict[str, Decimal] = {}
        self.signals: List[Signal] = []
        
        # Event callbacks
        self.on_signal_generated: Optional[Callable[[Signal], None]] = None
        
        # Performance tracking
        self.start_time: Optional[datetime] = None
        self.signal_count = 0
        self.trade_count = 0
    
    @abstractmethod
    def initialize(self, data: Dict[str, pd.DataFrame]) -> None:
        """Initialize the algorithm with historical data.
        
        Called once before trading begins. Use this to:
        - Pre-calculate indicators
        - Warm up machine learning models
        - Validate parameters
        
        Args:
            data: Dictionary of symbol -> OHLCV DataFrame for warmup period
        """
        pass
    
    @abstractmethod
    def on_data(self, data: Dict[str, pd.DataFrame]) -> Optional[Signal]:
        """Process new market data and generate trading signals.
        
        Called on each new bar/tick during trading. This is where
        the core strategy logic lives.
        
        Args:
            data: Dictionary of symbol -> OHLCV DataFrame (updated with latest data)
        
        Returns:
            Signal object if a trade should be executed, None otherwise
        """
        pass
    
    @abstractmethod
    async def on_execute(self, signal: Signal) -> Optional[Order]:
        """Execute a trading signal.
        
        Called when on_data() returns a signal. This method handles:
        - Risk checks via RiskManager
        - Position sizing
        - Order creation and submission
        
        Args:
            signal: Trading signal to execute
            
        Returns:
            Order object if order was submitted, None otherwise
        """
        pass
    
    @abstractmethod
    async def on_order_filled(self, order: Order) -> None:
        """Handle order fill events.
        
        Called when an order placed by this algorithm is filled.
        Use this to:
        - Update position tracking
        - Place stop-loss/take-profit orders
        - Update strategy state
        
        Args:
            order: Filled order details
        """
        pass
    
    async def execute_trade(
        self,
        symbol: str,
        side: OrderSide,
        quantity: Optional[Decimal] = None,
        price: Optional[Decimal] = None,
        order_type: OrderType = OrderType.MARKET,
        stop_loss_pct: Optional[float] = None,
        take_profit_pct: Optional[float] = None
    ) -> Optional[Order]:
        """Execute a trade with optional bracket orders.
        
        This is a convenience method that handles:
        - Position sizing (if quantity not provided)
        - Risk checks
        - Order submission
        - Bracket order creation (SL/TP)
        
        Args:
            symbol: Trading symbol
            side: Buy or sell
            quantity: Order quantity (auto-calculated if None)
            price: Limit price (for limit orders)
            order_type: Order type
            stop_loss_pct: Stop-loss percentage
            take_profit_pct: Take-profit percentage
            
        Returns:
            Order object if successful
        """
        if not self.order_manager:
            self.logger.error("execute_trade", "No order manager configured")
            return None
        
        # Get current price for calculations
        current_price = price or self.current_prices.get(symbol)
        if not current_price:
            self.logger.error("execute_trade", f"No price available for {symbol}")
            return None
        
        # Calculate position size if not provided
        if quantity is None:
            quantity = await self._calculate_position_size(symbol, side, current_price)
            if not quantity or quantity <= 0:
                return None
        
        # Check risk limits
        if not await self.risk_check(symbol, side, quantity, current_price):
            return None
        
        # Create order request
        request = OrderRequest(
            symbol=symbol,
            side=side,
            order_type=order_type,
            quantity=quantity,
            price=price,
            time_in_force=self._get_time_in_force(order_type),
            stop_loss_pct=stop_loss_pct,
            take_profit_pct=take_profit_pct,
            algorithm_id=self.config.name
        )
        
        try:
            # Use bracket orders if enabled and we have SL/TP
            if self.config.use_bracket_orders and (stop_loss_pct or take_profit_pct):
                bracket = await self.order_manager.submit_bracket_order(request)
                if bracket and bracket.entry_order:
                    self.trade_count += 1
                    return bracket.entry_order
            else:
                order = await self.order_manager.submit_order(request)
                if order:
                    self.trade_count += 1
                return order
                
        except Exception as e:
            self.logger.error("execute_trade", f"Trade execution failed: {e}")
        
        return None
    
    async def risk_check(
        self,
        symbol: str,
        side: OrderSide,
        quantity: Decimal,
        price: Decimal
    ) -> bool:
        """Perform pre-trade risk check.
        
        Args:
            symbol: Trading symbol
            side: Buy or sell
            quantity: Order quantity
            price: Order price
            
        Returns:
            True if trade passes all risk checks
        """
        if not self.risk_manager:
            return True
        
        # Check if trading is enabled
        if not self.risk_manager.can_trade():
            self.logger.risk_event("TRADE_BLOCKED", "Trading disabled by circuit breaker")
            return False
        
        # Check trade-specific risk
        allowed, reason = self.risk_manager.check_trade_risk(
            symbol=symbol,
            side=side,
            quantity=quantity,
            price=price
        )
        
        if not allowed:
            self.logger.risk_event("TRADE_REJECTED", reason or "Unknown risk violation")
            return False
        
        return True
    
    async def start(self) -> None:
        """Start the algorithm."""
        if self.state == AlgorithmState.INITIALIZING:
            self.logger.error("start", "Algorithm not initialized")
            return
        
        self.state = AlgorithmState.RUNNING
        self.start_time = datetime.now()
        
        # Register callbacks
        if self.order_manager:
            self.order_manager.on_order_filled = self._handle_order_filled
        
        self.logger.logger.info(f"Algorithm {self.config.name} started")
    
    async def stop(self) -> None:
        """Stop the algorithm."""
        self.state = AlgorithmState.STOPPED
        
        # Cancel any pending orders
        if self.order_manager:
            await self.order_manager.cancel_all_orders()
        
        self.logger.logger.info(f"Algorithm {self.config.name} stopped")
    
    async def pause(self) -> None:
        """Pause the algorithm."""
        if self.state == AlgorithmState.RUNNING:
            self.state = AlgorithmState.PAUSED
            self.logger.logger.info(f"Algorithm {self.config.name} paused")
    
    async def resume(self) -> None:
        """Resume the algorithm."""
        if self.state == AlgorithmState.PAUSED:
            self.state = AlgorithmState.RUNNING
            self.logger.logger.info(f"Algorithm {self.config.name} resumed")
    
    async def process_data(self, data: Dict[str, pd.DataFrame]) -> Optional[Signal]:
        """Process new data and execute any signals.
        
        This is the main entry point called by the trading engine.
        
        Args:
            data: Dictionary of symbol -> OHLCV DataFrame
            
        Returns:
            Signal if generated
        """
        if self.state != AlgorithmState.RUNNING:
            return None
        
        # Update stored data
        self.data = data
        
        # Update current prices
        for symbol, df in data.items():
            if not df.empty:
                self.current_prices[symbol] = Decimal(str(df['close'].iloc[-1]))
        
        # Generate signal
        signal = self.on_data(data)
        
        if signal:
            self.signal_count += 1
            self.signals.append(signal)
            
            # Log signal
            self.logger.signal(
                self.config.name,
                signal.symbol,
                signal.action,
                signal.confidence,
                signal.metadata
            )
            
            # Callback
            if self.on_signal_generated:
                try:
                    if asyncio.iscoroutinefunction(self.on_signal_generated):
                        await self.on_signal_generated(signal)
                    else:
                        self.on_signal_generated(signal)
                except Exception as e:
                    self.logger.error("callback", f"Signal callback error: {e}")
            
            # Execute signal
            if signal.action in ['buy', 'sell']:
                await self.on_execute(signal)
        
        return signal
    
    async def _handle_order_filled(self, order: Order) -> None:
        """Internal handler for order fills."""
        # Update positions
        if order.side == OrderSide.BUY:
            self.positions[order.symbol] = self.positions.get(order.symbol, Decimal("0")) + order.filled_quantity
        else:
            self.positions[order.symbol] = self.positions.get(order.symbol, Decimal("0")) - order.filled_quantity
        
        # Call user implementation
        await self.on_order_filled(order)
    
    async def _calculate_position_size(
        self,
        symbol: str,
        side: OrderSide,
        price: Decimal
    ) -> Decimal:
        """Calculate position size for a trade.
        
        Args:
            symbol: Trading symbol
            side: Buy or sell
            price: Current price
            
        Returns:
            Calculated position size
        """
        if not self.risk_manager:
            # Default sizing if no risk manager
            return Decimal("1.0")
        
        # Use risk manager to calculate size based on default stop loss
        stop_price = self.risk_manager.calculate_stop_loss(
            price, side, self.risk_manager.limits.stop_loss_default_pct
        )
        
        return self.risk_manager.calculate_position_size(price, stop_price)
    
    def _get_time_in_force(self, order_type: OrderType) -> Any:
        """Get default time in force for order type."""
        from adapters.base_adapter import TimeInForce
        
        if order_type == OrderType.MARKET:
            return TimeInForce.IOC
        return TimeInForce.GTC
    
    def get_parameters(self) -> Dict[str, Any]:
        """Get current algorithm parameters.
        
        Returns:
            Dictionary of parameter names and values
        """
        return {
            'name': self.config.name,
            'symbols': self.config.symbols,
            'timeframe': self.config.timeframe,
            'lookback_periods': self.config.lookback_periods,
            'use_bracket_orders': self.config.use_bracket_orders
        }
    
    def set_parameters(self, params: Dict[str, Any]) -> None:
        """Update algorithm parameters at runtime.
        
        Args:
            params: Dictionary of parameters to update
        """
        for key, value in params.items():
            if hasattr(self.config, key):
                setattr(self.config, key, value)
        
        self.logger.logger.info(f"Parameters updated: {params}")
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get algorithm performance statistics.
        
        Returns:
            Dictionary with performance metrics
        """
        runtime = None
        if self.start_time:
            runtime = (datetime.now() - self.start_time).total_seconds()
        
        return {
            'name': self.config.name,
            'state': self.state.value,
            'runtime_seconds': runtime,
            'signals_generated': self.signal_count,
            'trades_executed': self.trade_count,
            'current_positions': {
                symbol: float(qty) for symbol, qty in self.positions.items()
            },
            'symbols_tracked': list(self.data.keys())
        }
